name: Deploy
on: [push, workflow_dispatch]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Fetch code & checkout
              uses: actions/checkout@v4
            - name: Setup NodeJS
              uses: actions/setup-node@v4
            - name: Install dependencies, lint & test
              run: |
                npm install
                npm ci
    build:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Fetch code & checkout
              uses: actions/checkout@v4
            - name: Setup NodeJS
              uses: actions/setup-node@v4
            - name: Build app
              run: |
                npm install
                npm run build
    deploy:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Deploy
              run: echo "Deploying..."
